name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:10.15.2

    # strategy:
    #   matrix:
    #     node-version: [8.x, 10.x, 12.x]

    services:
      postgres:
        image: postgres:11.4
        ports:
        - 5432:5432

    steps:
    - uses: actions/checkout@v1
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ matrix.node-version }}

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        TEST_PG_HOST: postgres
        TEST_PG_PORT: ${{ job.services.postgres.ports['5432'] }}
        JOB_CONTEXT: ${{ toJson(job) }}
